# Generated by Django 3.2.8 on 2021-10-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, help_text='in US dollars $', max_digits=14)),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
