# Generated by Django 3.2.8 on 2021-10-07 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=15)),
                ('cost', models.DecimalField(decimal_places=2, help_text='in US dollars $', max_digits=14)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('card_number', models.CharField(max_length=100)),
                ('security_code', models.CharField(max_length=3)),
                ('expiration_date', models.DateField(default=datetime.date.today, help_text='use format MM/DD/YY', verbose_name='Date')),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
    ]
