# Generated by Django 3.2.8 on 2021-10-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='in US dollars $', max_digits=4),
        ),
        migrations.AlterField(
            model_name='soda',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='in US dollars $', max_digits=4),
        ),
    ]
